<?xml version='1.0'?>
 <package format='2'>
 <name>hpp-rerun</name>
 <version>5.1.0</version>
 <description>Display of hpp robots and obstacles in rerun </description>

 <maintainer email='hpp@laas.fr'>Joseph Mirabel</maintainer>
 <license>LGPL</license>

 <!-- <url type='website'>https://github.com/humanoid-path-planner/hpp-gepetto-viewer </url> -->

 <author>Joseph Mirabel</author>
 <author>Florent Lamiraux et al.</author>
 <exec_depend>hpp-corbaserver</exec_depend>
 </package>
